### ISSUE TITLE
Does not work on linux systems with kernel lockdown

### ISSUE THREAD

**Issue by idnovic** [X3n0m0rph59/precached#2] opened 2019-06-23 20:30 UTC
I installed precached via copr on fedora 30 but it does not work.

I used the following commands to activate it:
```
sudo systemctl enable --now precached.service
sudo systemctl enable --now precached-prime-caches.timer
systemctl --user enable --now precached-trigger.service
```

By does not work I mean:
precached service fails because of to many restart attemps
precached-prime-caches.timer failes because of missing dependencies

I need to deactivate all services to be able to login because boot never finishes.

**Comment by idnovic** [comment] 2019-06-23 20:32
Please let the system continue booting if an error happens. It does not make sense to hinder the system booting during a failed state of precached.

**Comment by X3n0m0rph59** [comment] 2019-06-24 05:19
Thanks for your report!

I have looked into it, but so far I am unable to reproduce a startup failure on a clean Fedora 30 virtual machine. I will test on a bare metal installation of Fedora 30 soon.

You are right, precached should definitely not stop the system from booting up in case of an error. I'm investigating what would be the optimal fix.

**Comment by idnovic** [comment] 2019-06-24 12:36
Thank you for answering, well I did install first time from the fedora 30 beta and modified the system till this date. Still I can not find the error. Tell me what I need to look for. The above errors are the only once in the systemctl status output.

**Comment by X3n0m0rph59** [comment] 2019-06-24 12:49
I managed to reproduce the problem by booting a Fedora 30 system with a deliberately corrupted `/etc/precached.conf` file. The daemon bails out, and gets restarted due to erroneous policy in `precached.service`, and then hangs the system completely.

To mitigate this issue you may do this:
`sudo systemctl edit --full precached.service`
Change the line reading:
`Restart=always`
to:
`Restart=no`

To check `/etc/precached.conf` for errors, you may invoke precached from the command line:
`$ precached`.

To clear all I/O trace logs you may run:
`sudo iotracectl clear`

To get full logs you may run:
`sudo journalctl -b -u precached.service`

Thanks again for reporting this issue, please tell me if that fixes your problem, so that I can prepare a new release!

**Comment by idnovic** [comment] 2019-06-24 13:27
I think I found the problem

`kernel: Lockdown: precached: Use of kprobes is restricted; see man kernel_lockdown.7`

So because I have secure boot enabled and I will not deactivate it. Is their something doable about this?
I would add an exception for precached but this seems not possible.

**Comment by idnovic** [comment] 2019-06-24 13:36
https://github.com/hirschmann/nbfc/issues/414#issuecomment-354274657
and
https://github.com/hirschmann/nbfc/issues/414#issuecomment-370253669

still do you need to use kprobes? Is their an alternative?

**Comment by idnovic** [comment] 2019-06-24 14:07
I think a signed kernel module may work. Is the responsible file of precached a kernel module?
I would try to sign it.

https://github.com/linuxwacom/input-wacom/wiki/Kernel-Module-Signing

**Comment by X3n0m0rph59** [comment] 2019-06-24 15:15
Ah OK, secure boot systems with Linux lockdown patches applied are currently not supported, but I am definitely planning to look into this.

I'm currently preparing a Fedora 30 virtual machine with secure boot enabled. 

I would prefer not to have to end up providing a signed kernel module. Maybe I can work around the need to use kprobes somehow. I will investigate...

**Comment by X3n0m0rph59** [comment] 2019-06-24 15:35
> I think I found the problem
> 
> `kernel: Lockdown: precached: Use of kprobes is restricted; see man kernel_lockdown.7`
> 

Yes you are right, I am able to reproduce this now on my virtual machine.

> So because I have secure boot enabled and I will not deactivate it. Is their something doable about this?
> I would add an exception for precached but this seems not possible.

Sadly, that's not possible at the moment.

**Comment by idnovic** [comment] 2019-06-24 15:47
Even if I can only help with testing i would be interested in the technical details of what you may find out.
I was not able to find a list of working trace or debugging interfaces while in lockdown mode.

I would not mind to sign it myself, your only option when a signed module is needed is to get the distributors to package precached and sign it with their keys. As an end user I would need to roll my own keys for the whole trusted chain. I wanted to create my own linux kernel build so that is something I need to do anyway but for every other user this is to much.

**Comment by idnovic** [comment] 2019-06-24 15:52
I do understand the different opinions on the lockdown mode beeing enabled while in secureboot.
It is a controversial matter. But after I saw the list of locked down kernel interfaces I would not want to deactivate it. It does improve security.

**Comment by idnovic** [comment] 2019-06-24 15:55
to add to the signing part, you can not just sign the module with any key. It needs to be trusted by the trust chain. Maybe not on efi level but the kernel needs to trust it.

**Comment by X3n0m0rph59** [comment] 2019-06-27 13:16
I have made some progress on this issue...

I have implemented a new, Linux 'fanotify' based tracer, that does not require 'ftrace' or 'kprobes' support to be present on the system.

**Comment by idnovic** [comment] 2019-06-28 10:56
I would like to test it. Can you update your copr repo, please?

**Comment by X3n0m0rph59** [comment] 2019-06-28 13:04
Yes! The Fedora copr repository now has a fresh build of precached that uses the new `fanotify` based tracer.

Please install the package `precached-git`, version 1.7.0-6.
The command `precached --version` should report: `1.7.0`

Please note that version 1.7.0 introduces a binary format change of `*.trace` files, so you will have to clear your previously generated trace logs, or you will experience errors:

`sudo iotracectl clear`

Note: If you want to submit further bug reports, it would be great if you could include log output:

`sudo journalctl -b -u precached.service`

To set the log-level to something reasonable for debugging, please set it to `debug` via:

`sudoedit /etc/precached/log4rs.yaml`

Please change line 30:

From: 
`level: warn`

To:
`level: debug`

Remarks:
The thread named `precached/fanotify` still crashes sometimes for a yet to be discovered reason. Then you will have to restart precached, or it will stop generating traces until the next re-boot:

`sudo systemctl restart precached`
`precached-trigger transition-profile`

To test precached's effectiveness you may run a command like this one:

`perf stat -e 'major-faults,minor-faults' libreoffice --calc`

or, if you need to be root:

`sudo perf stat -e 'major-faults,minor-faults' sudo -u username libreoffice --calc`

Thank you for testing!

**Comment by X3n0m0rph59** [comment] 2019-06-29 04:56
The package `precached-git-1.7.0-7` should fix the fanotify thread's crasher bug!

**Comment by idnovic** [comment] 2019-06-29 15:02
Thank you!

It seems to work now. The precached GUI has problems, only overview and events show stuff. Cache, statistics and internal state are empty.

I want it to run for a few days until I get back to you.

**Comment by X3n0m0rph59** [comment] 2019-06-29 17:41
Nice!

The utilities `precachedtop` and `precached-gui` as well, are still very much a work-in-progress.
(Where `precached-gui` is even more lagging than `precachedtop`)

Please get back to me, on what feature you require!

**Comment by idnovic** [comment] 2019-06-29 19:25
with precachedtop I have zero files in cache. What is the right command to view cached files? Or better asked how do I know it is working?

**Comment by X3n0m0rph59** [comment] 2019-06-30 06:23
To verify that precached is indeed working as intended, you may want to check if a file is loaded into the Linux kernel's page cache:

```
$ sudo fincore /usr/lib/libreoffice/program/soffice.bin
  RES PAGES  SIZE FILE
  16K     4 13,8K /usr/lib/libreoffice/program/soffice.bin
```
(Needs to be run as root, otherwise it will show invalid values for security reasons)
The column `RES` shows the resident (cached) size of the file. If it reads 0 the file is NOT cached.

This of course only works if you did not run/read the binary/file before, since then it would be in the cache.
The kernel's page cache can be cleared by using the following command:

`$ sudo sh -c 'echo 3 > /proc/sys/vm/drop_caches'`
(This simulates eviction of pages from the cache, like it happens when a memory hog process is running)

If precached decided that a file is worth keeping (e.g.: part of your desktop session), then it will stay in memory.

To show the number of cache misses on program execution, you may use this command:
```
$ perf stat -e 'major-faults,minor-faults' libreoffice --calc

 Performance counter stats for 'libreoffice --calc':

                 5      major-faults:u                                              
            33.131      minor-faults:u                                              

       1,833349519 seconds time elapsed

       0,985122000 seconds user
       0,131403000 seconds sys
```
This program execution incurred 5 major page faults (disk accesses)

```
$ sudo systemctl stop precached
$ sudo sh -c 'echo 3 > /proc/sys/vm/drop_caches'`
$ perf stat -e 'major-faults,minor-faults' libreoffice --calc

Performance counter stats for 'libreoffice --calc':

             1.222      major-faults:u                                              
            33.219      minor-faults:u                                              

       2,999699945 seconds time elapsed

       1,193392000 seconds user
       0,204084000 seconds sys
```
(Without precached, the program execution incurred 1.222 major page faults (disk accesses))

## precachedtop
Additionally, I reworked the code that tracks cached files. The companion tool `precachedtop` now shows each and every file cached by precached, not just a subset like it did before.
The code is included in the package `precached-git` >= `1.7.0-8`.

**Comment by X3n0m0rph59** [comment] 2019-06-30 06:29
On Fedora 30, please use the following path to find LibreOffice:
```
$ sudo fincore /usr/lib64/libreoffice/program/soffice.bin
```

**Comment by idnovic** [comment] 2019-06-30 20:20
I am still testing but precachedtop still does not display cached files for me.

I tried to open nautilus, checked the kernel cache as you recommended above and the file is still cached after I closed nautilus. Then I dropped caches and nautilus was not cached anymore. 

From my understanding precached should have cached nautilus again since I use it all the time but it did not.

I have 4GB Ram. I use a swap partition and preferred over the swap partition I also use zram (lz4 compressed ram block).

What settings for the memory do you recommed for precached? I tried 95% 85% 75% in the precached config file. Maybe precached is not caching because I use the lz4 zram .

```
$ swapon -s
Dateiname				Typ		Größe	Benutzt	Priorität
/dev/mmcblk0p3                         	partition	4194300	0	-2
/dev/zram0                             	partition	1846676	250112	1000

```
```
$ zramctl
NAME       ALGORITHM DISKSIZE   DATA COMPR TOTAL STREAMS MOUNTPOINT
/dev/zram0 lz4           1,8G 242,6M   72M   76M       4 [SWAP]
```

**Comment by X3n0m0rph59** [comment] 2019-07-01 05:15
Yes, your understanding regarding the caching of nautilus is correct! It should have stayed in the cache.

Zram should definitely not prevent precached from caching! It may interfere with the memory pressure logic of precached though. I will investigate this...

I suspect that precached on your system is unable to write out trace logs.
This command should list hundreds of logs, after a few days of operation:

`$ sudo iotracectl list`

Could you please double check that your systemd .service file does not contain any of these lines:
```
PrivateDevices=yes
PrivateTmp=yes
ProtectSystem=full
```

You can edit the precached.service file with this command:

`sudo systemctl edit --full precached.service`

If so, please remove these 3 lines completely and save the file.

Afterwards, you may restart precached:
```
$ sudo systemctl restart precached.service
$ precached-trigger transition-profile
```

It should not take more than one minute of wall clock time until the first trace log will be generated.
(After you ran a few desktop apps)
Please verify again, by using this command:

`$ sudo iotracectl list`

## Background

The new fanotify based tracer needs to process file descriptors, and additionally needs to place a watch for "file open" events on your root filesystem, which is prevented by all of the three lines listed above.

**Comment by idnovic** [comment] 2019-07-01 05:45
```
$ sudo iotracectl list
precached Copyright (C) 2017-2019 the precached team    
Dieses Programm kommt OHNE JEGLICHE GARANTIE;
Dies ist freie Software, die Sie gerne weiter verbreiten dürfen,
unter den Bedingungen der Lizenz



Keine I/O Trace Logs gefunden
```

You suspected right.
Yes I have now files in my cache!

**Comment by idnovic** [comment] 2019-07-01 05:53
> The new fanotify based tracer needs to process file descriptors, and additionally needs to place a watch for "file open" events on your root filesystem, which is prevented by all of the three lines listed above.

What security implications can this have?
Also precached runs as root, maybe use an extra user?
Optionally maybe add a selinux profile.

Is it possible to not run precached as root?

**Comment by idnovic** [comment] 2019-07-01 05:58
`precached::plugins::rule_engine:263 - Ignored 'CacheMetadataRecursive' rule action, current system profile does not allow offline prefetching`

only remaining error after I restarted precached service

**Comment by X3n0m0rph59** [comment] 2019-07-01 06:10
> precached::plugins::rule_engine:263 - Ignored 'CacheMetadataRecursive' rule action, current system profile does not allow offline prefetching

This non-critical warning is printed whenever precached operates In "online prefetch only" mode and precached refrained from doing a "offline prefetch" operation like caching files ahead of program execution, or metadata caching.

precached switches its operational profile (enables "offline prefetching" too) when you run the command:

`$ precached-trigger transition-profile`

To verify that precached is indeed running in the intended mode of operation, you may execute this command:

`$ precachedctl plugins analyze internal-state`

`profiles.current_profile` should be set to `UpAndRunning`

**Comment by idnovic** [comment] 2019-07-01 14:54
Everything seems to work fine, I still need to figure out what good memory settings via sysctl should be set. 

About the memory settings I can set in precached config,
the lower barrier is what % of memory to fill up with cached files. 

What are the 2 other variables for? Or how do the 3 work together?

**Comment by X3n0m0rph59** [comment] 2019-07-01 16:06
> Everything seems to work fine

Glad to hear this!

> About the memory settings I can set in precached config, the lower barrier is what % of memory to fill up with cached files.

> What are the 2 other variables for? Or how do the 3 work together?

I did a (short) writeup, please find it here:
[Configuration-best-practices](https://github.com/X3n0m0rph59/precached/wiki/Configuration-best-practices)

**Comment by idnovic** [comment] 2019-07-01 16:47
```
available_mem_critical_threshold=60
available_mem_upper_threshold=20
available_mem_lower_threshold=10
```

okay so the above means cache up to 20% of memory with precached, if the whole mem usage is above 60% drop precached mem usage to 10%?

**Comment by X3n0m0rph59** [comment] 2019-07-01 17:01
> ```
> available_mem_critical_threshold=60
> available_mem_upper_threshold=20
> available_mem_lower_threshold=10
> ```
> 
> okay so the above means cache up to 20% of memory with precached, if the whole mem usage is above 60% drop precached mem usage to 10%?

Yes, that's correct!

**Comment by idnovic** [comment] 2019-07-01 17:19
Okay here is what I want to accomplish:
4GB mem, lets use 3.7GB because my integrated gpu needs mem too.
After a restart mem usage is around 1.2GB. Leaves 2.5GB to be used.
But I only want to cache up to 500MB because I want to be able to run any vm (max 2GB virt mem) without much swapping.

While I am not running any vm, I do not mind more cached files.
My constrains are 1.2GB system idle + 500MB of cacheable mem, leaves 2GB for heavy stuff
But while mem usage is more than 2.5GB (1,2GB system idle, 500MB cache, + starting vm/heavy app) I did like that precached drops all cached files before I need to swap.

```
available_mem_critical_threshold=70
available_mem_upper_threshold=15
available_mem_lower_threshold=1
```

the above settings seem more fitting?

Is precached just using these % as hard numbers or some sort of linear calculation?

**Comment by X3n0m0rph59** [comment] 2019-07-02 05:08
> But I only want to cache up to 500MB because I want to be able to run any vm (max 2GB virt mem) 

The intended use case ist to **NOT** factor in things like memory consumption of VMs, but to let precached detect memory pressure, and then let precached free memory as needed. This way one achieves near optimal results of what could be achieved considering the available amount of RAM.
**BUT**, precached needs a short amount of time to react to memory pressure, so we have to shrink faster than the other processes consume memory.


> without much swapping.

If we start swapping to disk, we killed performance completely. If we started swapping out due to a slow reaction time of precached, it would actually have done more harm than good.

The recommended configuration in your case would be:

```
available_mem_critical_threshold=80
available_mem_upper_threshold=75
available_mem_lower_threshold=15
```

The reasoning behind this:

`available_mem_critical_threshold=80`: As high as possible, hopefully gives enough headroom for fast growing processes, so that the system wont swap out pages in case precached can't free them as fast as the other process dirties memory. Reduce this if precached does not shrink fast enough.

`available_mem_upper_threshold=75`: Set this as high as possible. It would be optimal, if your core desktop files would fit into this. Reduce this if precached does not shrink fast enough.

`available_mem_lower_threshold=15`: Quickly shrink in case we are under pressure, since you intend to use a huge working set (VM, 2GiB) with around 4GiB of installed RAM.

> Is precached just using these % as hard numbers or some sort of linear calculation?

Just hard numbers. No fancy calculations done besides polling memory statistics.

Please let me know if this actually works for you _in practice_, and from when you notice sluggish system response!

You may want to use the tools htop2, glances and something like `watch -n0.5 cat /proc/meminfo`

I am currently preparing a test setup (bare metal, an old laptop) with a Fedora 30 installation, where I want to replicate your intended use case.

**Comment by idnovic** [comment] 2019-07-02 11:01
Thank you. I will try your suggested settings.
Yesterday precached did not give memory back. What happened was I had 65% mem usage all included. I started a vm. the vm grows to 2GB. Mem usage hit 99% and swap usage increased. But precached did not seem to want to give memory back. So I stopped precached service and got 65% mem usage (with vm running). So I think the system swapped "everything" but the vm and precached. the vm needs 50%(2GB) mem. The other 15% were the system after I killed precached. My normal system uses 30% mem after restart, so half of the normal system were swapped because precached did not seem to unload cached files. I looked at precachedtop and I had over 2000 files in cache while the vm was running.

I am sure even though I only have 4GB ram that my setup is enough for my desktop + 1 vm.
Without precached I used to have 85% mem usage including desktop and 1 vm, no swapping.

4GB real mem (3.7 because gpu mem), around 0.9GB zram (lz4), 4GB swap partition

You can install zram from the `zram` and `zram-systemd` package. In `/etc/zram` you need to set the right `FACTOR`, I have `4`. Then start the `zram-swap.service`

**Comment by idnovic** [comment] 2019-07-02 11:08
Do I need to set values of:

```
available_mem_critical_threshold=80
available_mem_upper_threshold=75
```

near each other or can they have a bigger gab in between?
Is 70 and 40 possible or only 70 and 65?

**Comment by idnovic** [comment] 2019-07-02 11:10
For the vm just create a vm with virt-manager, any linux will do and set it to 2GB ram.
Maybe precached does not like zram.

Thank you!

**Comment by idnovic** [comment] 2019-07-02 21:08
```
available_mem_critical_threshold=65
available_mem_upper_threshold=25
available_mem_lower_threshold=5
```

That is what I am testing now.
After restart with precached files I have 45% mem usage instead of 30-35%. But I also have enough room for my vm. Your suggestion had 60% mem usage after restart. Okay as long as I figure out how to drop cached files for the vm.

1600 cached files.
Can I view the files which are precached but not used?
Or are files in use not listed under cached files anymore?

**Comment by idnovic** [comment] 2019-07-02 21:22
Started vm, 97-99% mem usage. Swapped and precached still has 1600 files in the cache.
Are you sure this is not java? :)
I only know java that keeps mem for itself.
I want to try without zram tomorrow and see if that changes anything.

Okay I need to add that this time not the swap device was used for swapping but zram. That is what I want. Going to play with swappiness too.

**Comment by idnovic** [comment] 2019-07-02 22:15
![Bildschirmfoto vom 2019-07-03 00-03-14](https://user-images.githubusercontent.com/28260793/60550254-af30b100-9d27-11e9-9555-57adb4520cad.png)
![Bildschirmfoto vom 2019-07-03 00-02-30](https://user-images.githubusercontent.com/28260793/60550255-af30b100-9d27-11e9-9801-cfafee7fd74f.png)
![Bildschirmfoto vom 2019-07-03 00-02-06](https://user-images.githubusercontent.com/28260793/60550257-afc94780-9d27-11e9-81a2-34ca56fb89b5.png)
![Bildschirmfoto vom 2019-07-03 00-01-11](https://user-images.githubusercontent.com/28260793/60550259-afc94780-9d27-11e9-8726-24ccc6c63a61.png)

**Comment by X3n0m0rph59** [comment] 2019-07-03 16:29
I was able to reproduce this, precached does not free memory at all for some reason.

**Comment by idnovic** [comment] 2019-07-03 16:32
I updated the zram settings in the above posts to reflect my latest changes.
https://github.com/X3n0m0rph59/precached/issues/2#issuecomment-507627059

**Comment by idnovic** [comment] 2019-07-03 16:34
In case you missed it on the other issue report, the slow shutdown happens even with precached disabled. So let it be as it is. No need to rewrite that part.

**Comment by X3n0m0rph59** [comment] 2019-07-03 17:04
Thanks for investigating this!

**Comment by X3n0m0rph59** [comment] 2019-07-06 06:08
> Started vm, 97-99% mem usage. Swapped and precached still has 1600 files in the cache.
Are you sure this is not java? :)

Yes! :-)

This should be fixed now, in the latest build. The root cause of this issue was a thread deadlock bug. The same bug was the culprit in causing issue #10. Whenever the thread deadlock was triggered, precached stopped notifying its internal plugins of memory state changes. This has been fixed by switching the internal state handling to lock free data structures.

I did extensive testing using my secure boot enabled Fedora 30 VM.
Additionally I configured ZRAM swapping as suggested.

If you want to replicate my test scenario, you may use the below script to allocate variable amounts of memory:

```bash
$ count=$((1000*1500)); dd if=/dev/zero bs=1024 count=$count | pv -b -B $((1024*$count)) | dd of=/dev/shm/fill bs=2k
```
This will allocate 1500 MB of memory, or up to the max. limits of the /dev/shm/ filesystem.
```bash
$ rm /dev/shm/fill
```
This will de-allocate the previously allocated memory.

You may play with the amount of allocated memory, and watch `precachedtop` allocate and de-allocate files in the `mlock()`ed cache area.

Since precached won't perform offline-prefetching when in BootUp profile, please be sure to run:
```bash
$ precached-trigger transition-profile
```
(Only needed if you manually restarted precached)

My updated recommended `precached.conf` memory configuration in your case would be:

```
available_mem_critical_threshold=90
available_mem_upper_threshold=85
available_mem_lower_threshold=60
```

The reasoning behind this:

`available_mem_critical_threshold=90`: May be set this high, since ZRAM compressed swapping will compensate for fast growing memory hogs.

`available_mem_upper_threshold=85`: Set as high as possible. It would be optimal, if your core desktop files would fit into this. (Will be dynamically de-allocated, if needed)

`available_mem_lower_threshold=60`: If we are below this threshold, start filling up the cache again. The previously suggested value was way too low, and barely reachable.

The spread between `available_mem_lower_threshold` and `available_mem_upper_threshold` should be large enough (approx. >5), so that the system wont start bouncing between the lower and upper threshold states.

**Comment by X3n0m0rph59** [comment] 2019-07-08 08:22
Closing this bug report now, please re-open if it is still not resolved for you!

**Closed as completed by X3n0m0rph59** 2019-07-08 08:22 UTC
Labels: bug
